/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SmartRule = IDL.Record({
  'ruleName' : IDL.Text,
  'action' : IDL.Text,
  'active' : IDL.Bool,
  'createdBy' : IDL.Text,
  'deviceId' : IDL.Text,
  'users' : IDL.Vec(IDL.Text),
  'schedule' : IDL.Text,
  'triggers' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TimeSlot = IDL.Record({
  'day' : IDL.Nat,
  'endHour' : IDL.Nat,
  'startHour' : IDL.Nat,
});
export const UserAccess = IDL.Record({
  'accessLevel' : UserRole,
  'rfidUid' : IDL.Text,
  'accessWindow' : IDL.Vec(TimeSlot),
  'name' : IDL.Text,
  'role' : UserRole,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'pinCode' : IDL.Text,
  'failedAttempts' : IDL.Nat,
  'lastAccess' : IDL.Int,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Subtask = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'completed' : IDL.Bool,
});
export const AccessEvent = IDL.Record({
  'rfidUid' : IDL.Text,
  'method' : IDL.Text,
  'userEmail' : IDL.Text,
  'timestamp' : IDL.Int,
  'success' : IDL.Bool,
  'location' : IDL.Text,
  'eventType' : IDL.Text,
});
export const DeviceStatus = IDL.Record({
  'batteryLevel' : IDL.Nat,
  'tamperDetected' : IDL.Bool,
  'wifiSignalStrength' : IDL.Int,
  'isLocked' : IDL.Bool,
  'emergencyMode' : IDL.Bool,
  'firmwareVersion' : IDL.Text,
  'lastSync' : IDL.Int,
  'currentUsers' : IDL.Nat,
});
export const Time = IDL.Int;
export const DeviceInfo = IDL.Record({
  'status' : DeviceStatus,
  'isConnected' : IDL.Bool,
  'deviceId' : IDL.Text,
  'deviceName' : IDL.Text,
  'lastSync' : Time,
});
export const UserProfile = IDL.Record({
  'rfidUid' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const LogEvent = IDL.Record({
  'code' : IDL.Text,
  'level' : IDL.Text,
  'message' : IDL.Text,
  'deviceId' : IDL.Text,
  'timestamp' : Time,
});
export const UserStats = IDL.Record({
  'totalCompleted' : IDL.Nat,
  'lastCompletedDate' : IDL.Opt(IDL.Int),
  'unlockedBadges' : IDL.Vec(IDL.Text),
  'longestStreak' : IDL.Nat,
  'currentStreak' : IDL.Nat,
  'points' : IDL.Nat,
});
export const SmartRuleLog = IDL.Record({
  'ruleName' : IDL.Text,
  'triggerCondition' : IDL.Text,
  'timestamp' : Time,
  'outcome' : IDL.Bool,
  'actionTaken' : IDL.Text,
});
export const ToDo = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'timeSpent' : IDL.Nat,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Text,
  'timerSeconds' : IDL.Opt(IDL.Nat),
  'category' : IDL.Text,
  'priority' : Priority,
  'subtasks' : IDL.Vec(Subtask),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDevice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addSmartRule' : IDL.Func([SmartRule], [], []),
  'addUser' : IDL.Func([UserAccess], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignDeviceToAdmin' : IDL.Func([IDL.Text], [], []),
  'completeTodo' : IDL.Func([IDL.Nat], [], []),
  'createDefaultStats' : IDL.Func([], [], []),
  'createTodo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Priority,
        IDL.Text,
        IDL.Opt(IDL.Int),
        IDL.Vec(Subtask),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteTodo' : IDL.Func([IDL.Nat], [], []),
  'disableUser' : IDL.Func([IDL.Text], [], []),
  'disableVacationMode' : IDL.Func([], [], []),
  'enableUser' : IDL.Func([IDL.Text], [], []),
  'enableVacationMode' : IDL.Func([], [], []),
  'finishTimer' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'getAccessEvents' : IDL.Func([], [IDL.Vec(AccessEvent)], ['query']),
  'getAdminDashboardData' : IDL.Func(
      [],
      [
        IDL.Record({
          'activeUsers' : IDL.Nat,
          'vacationMode' : IDL.Bool,
          'disabledUsers' : IDL.Nat,
          'failedAccessLast24h' : IDL.Nat,
          'accessEventFeed' : IDL.Vec(AccessEvent),
          'deviceStatuses' : IDL.Vec(IDL.Tuple(IDL.Text, DeviceStatus)),
          'guestUsers' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'activeSmartRulesCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllDeviceStatuses' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, DeviceStatus))],
      ['query'],
    ),
  'getAllDevices' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, DeviceInfo))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDefaultDeviceStatus' : IDL.Func([], [DeviceStatus], ['query']),
  'getDeviceById' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'id' : IDL.Text,
          'status' : DeviceStatus,
          'name' : IDL.Text,
          'isConnected' : IDL.Bool,
          'lastSync' : Time,
        }),
      ],
      ['query'],
    ),
  'getDeviceCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getDeviceList' : IDL.Func([], [IDL.Vec(DeviceInfo)], ['query']),
  'getDeviceNameCache' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getDeviceStatsById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DeviceStatus)],
      ['query'],
    ),
  'getDeviceStatusById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DeviceStatus)],
      ['query'],
    ),
  'getEventLogs' : IDL.Func([], [IDL.Vec(LogEvent)], ['query']),
  'getFailedAccessEventsLast24h' : IDL.Func(
      [],
      [IDL.Vec(AccessEvent)],
      ['query'],
    ),
  'getMyStats' : IDL.Func([], [UserStats], ['query']),
  'getSecurityDecoyStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getSmartRuleExecutionLog' : IDL.Func([], [IDL.Vec(SmartRuleLog)], ['query']),
  'getSmartRules' : IDL.Func([], [IDL.Vec(SmartRule)], ['query']),
  'getTodoStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'pending' : IDL.Nat,
          'completed' : IDL.Nat,
          'overdue' : IDL.Nat,
          'urgent' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTodos' : IDL.Func([], [IDL.Vec(ToDo)], ['query']),
  'getTodosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(ToDo)], ['query']),
  'getUserAccessWindow' : IDL.Func([IDL.Text], [IDL.Vec(TimeSlot)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsers' : IDL.Func([], [IDL.Vec(UserAccess)], ['query']),
  'getVacationModeStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isDeviceAdmin' : IDL.Func([IDL.Text], [], ['query']),
  'logSmartRuleExecution' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'recordAccessEvent' : IDL.Func([AccessEvent], [], []),
  'removeSmartRule' : IDL.Func([IDL.Text], [], []),
  'removeUser' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserAccessWindow' : IDL.Func([IDL.Text, IDL.Vec(TimeSlot)], [], []),
  'simulateAccessAttempt' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'startTimer' : IDL.Func([IDL.Nat], [], []),
  'syncDevice' : IDL.Func([IDL.Text], [], []),
  'toggleDefaultDeviceLock' : IDL.Func([], [], []),
  'toggleDeviceLock' : IDL.Func([IDL.Text], [], []),
  'toggleHolidayLights' : IDL.Func([IDL.Bool], [], []),
  'updateDeviceStatus' : IDL.Func([IDL.Text, DeviceStatus], [], []),
  'updateTodo' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
        IDL.Opt(Priority),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Vec(Subtask)),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SmartRule = IDL.Record({
    'ruleName' : IDL.Text,
    'action' : IDL.Text,
    'active' : IDL.Bool,
    'createdBy' : IDL.Text,
    'deviceId' : IDL.Text,
    'users' : IDL.Vec(IDL.Text),
    'schedule' : IDL.Text,
    'triggers' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TimeSlot = IDL.Record({
    'day' : IDL.Nat,
    'endHour' : IDL.Nat,
    'startHour' : IDL.Nat,
  });
  const UserAccess = IDL.Record({
    'accessLevel' : UserRole,
    'rfidUid' : IDL.Text,
    'accessWindow' : IDL.Vec(TimeSlot),
    'name' : IDL.Text,
    'role' : UserRole,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'pinCode' : IDL.Text,
    'failedAttempts' : IDL.Nat,
    'lastAccess' : IDL.Int,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Subtask = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'completed' : IDL.Bool,
  });
  const AccessEvent = IDL.Record({
    'rfidUid' : IDL.Text,
    'method' : IDL.Text,
    'userEmail' : IDL.Text,
    'timestamp' : IDL.Int,
    'success' : IDL.Bool,
    'location' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const DeviceStatus = IDL.Record({
    'batteryLevel' : IDL.Nat,
    'tamperDetected' : IDL.Bool,
    'wifiSignalStrength' : IDL.Int,
    'isLocked' : IDL.Bool,
    'emergencyMode' : IDL.Bool,
    'firmwareVersion' : IDL.Text,
    'lastSync' : IDL.Int,
    'currentUsers' : IDL.Nat,
  });
  const Time = IDL.Int;
  const DeviceInfo = IDL.Record({
    'status' : DeviceStatus,
    'isConnected' : IDL.Bool,
    'deviceId' : IDL.Text,
    'deviceName' : IDL.Text,
    'lastSync' : Time,
  });
  const UserProfile = IDL.Record({
    'rfidUid' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const LogEvent = IDL.Record({
    'code' : IDL.Text,
    'level' : IDL.Text,
    'message' : IDL.Text,
    'deviceId' : IDL.Text,
    'timestamp' : Time,
  });
  const UserStats = IDL.Record({
    'totalCompleted' : IDL.Nat,
    'lastCompletedDate' : IDL.Opt(IDL.Int),
    'unlockedBadges' : IDL.Vec(IDL.Text),
    'longestStreak' : IDL.Nat,
    'currentStreak' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const SmartRuleLog = IDL.Record({
    'ruleName' : IDL.Text,
    'triggerCondition' : IDL.Text,
    'timestamp' : Time,
    'outcome' : IDL.Bool,
    'actionTaken' : IDL.Text,
  });
  const ToDo = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'timeSpent' : IDL.Nat,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Text,
    'timerSeconds' : IDL.Opt(IDL.Nat),
    'category' : IDL.Text,
    'priority' : Priority,
    'subtasks' : IDL.Vec(Subtask),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDevice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addSmartRule' : IDL.Func([SmartRule], [], []),
    'addUser' : IDL.Func([UserAccess], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignDeviceToAdmin' : IDL.Func([IDL.Text], [], []),
    'completeTodo' : IDL.Func([IDL.Nat], [], []),
    'createDefaultStats' : IDL.Func([], [], []),
    'createTodo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Priority,
          IDL.Text,
          IDL.Opt(IDL.Int),
          IDL.Vec(Subtask),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteTodo' : IDL.Func([IDL.Nat], [], []),
    'disableUser' : IDL.Func([IDL.Text], [], []),
    'disableVacationMode' : IDL.Func([], [], []),
    'enableUser' : IDL.Func([IDL.Text], [], []),
    'enableVacationMode' : IDL.Func([], [], []),
    'finishTimer' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getAccessEvents' : IDL.Func([], [IDL.Vec(AccessEvent)], ['query']),
    'getAdminDashboardData' : IDL.Func(
        [],
        [
          IDL.Record({
            'activeUsers' : IDL.Nat,
            'vacationMode' : IDL.Bool,
            'disabledUsers' : IDL.Nat,
            'failedAccessLast24h' : IDL.Nat,
            'accessEventFeed' : IDL.Vec(AccessEvent),
            'deviceStatuses' : IDL.Vec(IDL.Tuple(IDL.Text, DeviceStatus)),
            'guestUsers' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'activeSmartRulesCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllDeviceStatuses' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, DeviceStatus))],
        ['query'],
      ),
    'getAllDevices' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, DeviceInfo))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDefaultDeviceStatus' : IDL.Func([], [DeviceStatus], ['query']),
    'getDeviceById' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'id' : IDL.Text,
            'status' : DeviceStatus,
            'name' : IDL.Text,
            'isConnected' : IDL.Bool,
            'lastSync' : Time,
          }),
        ],
        ['query'],
      ),
    'getDeviceCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getDeviceList' : IDL.Func([], [IDL.Vec(DeviceInfo)], ['query']),
    'getDeviceNameCache' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getDeviceStatsById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DeviceStatus)],
        ['query'],
      ),
    'getDeviceStatusById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DeviceStatus)],
        ['query'],
      ),
    'getEventLogs' : IDL.Func([], [IDL.Vec(LogEvent)], ['query']),
    'getFailedAccessEventsLast24h' : IDL.Func(
        [],
        [IDL.Vec(AccessEvent)],
        ['query'],
      ),
    'getMyStats' : IDL.Func([], [UserStats], ['query']),
    'getSecurityDecoyStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getSmartRuleExecutionLog' : IDL.Func(
        [],
        [IDL.Vec(SmartRuleLog)],
        ['query'],
      ),
    'getSmartRules' : IDL.Func([], [IDL.Vec(SmartRule)], ['query']),
    'getTodoStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'pending' : IDL.Nat,
            'completed' : IDL.Nat,
            'overdue' : IDL.Nat,
            'urgent' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTodos' : IDL.Func([], [IDL.Vec(ToDo)], ['query']),
    'getTodosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(ToDo)], ['query']),
    'getUserAccessWindow' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TimeSlot)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsers' : IDL.Func([], [IDL.Vec(UserAccess)], ['query']),
    'getVacationModeStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isDeviceAdmin' : IDL.Func([IDL.Text], [], ['query']),
    'logSmartRuleExecution' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'recordAccessEvent' : IDL.Func([AccessEvent], [], []),
    'removeSmartRule' : IDL.Func([IDL.Text], [], []),
    'removeUser' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserAccessWindow' : IDL.Func([IDL.Text, IDL.Vec(TimeSlot)], [], []),
    'simulateAccessAttempt' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'startTimer' : IDL.Func([IDL.Nat], [], []),
    'syncDevice' : IDL.Func([IDL.Text], [], []),
    'toggleDefaultDeviceLock' : IDL.Func([], [], []),
    'toggleDeviceLock' : IDL.Func([IDL.Text], [], []),
    'toggleHolidayLights' : IDL.Func([IDL.Bool], [], []),
    'updateDeviceStatus' : IDL.Func([IDL.Text, DeviceStatus], [], []),
    'updateTodo' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
          IDL.Opt(Priority),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Vec(Subtask)),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };