/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccessEvent {
  'rfidUid' : string,
  'method' : string,
  'userEmail' : string,
  'timestamp' : bigint,
  'success' : boolean,
  'location' : string,
  'eventType' : string,
}
export interface DeviceInfo {
  'status' : DeviceStatus,
  'isConnected' : boolean,
  'deviceId' : string,
  'deviceName' : string,
  'lastSync' : Time,
}
export interface DeviceStatus {
  'batteryLevel' : bigint,
  'tamperDetected' : boolean,
  'wifiSignalStrength' : bigint,
  'isLocked' : boolean,
  'emergencyMode' : boolean,
  'firmwareVersion' : string,
  'lastSync' : bigint,
  'currentUsers' : bigint,
}
export interface LogEvent {
  'code' : string,
  'level' : string,
  'message' : string,
  'deviceId' : string,
  'timestamp' : Time,
}
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface SmartRule {
  'ruleName' : string,
  'action' : string,
  'active' : boolean,
  'createdBy' : string,
  'deviceId' : string,
  'users' : Array<string>,
  'schedule' : string,
  'triggers' : Array<string>,
}
export interface SmartRuleLog {
  'ruleName' : string,
  'triggerCondition' : string,
  'timestamp' : Time,
  'outcome' : boolean,
  'actionTaken' : string,
}
export interface Subtask {
  'id' : bigint,
  'text' : string,
  'completed' : boolean,
}
export type Time = bigint;
export interface TimeSlot {
  'day' : bigint,
  'endHour' : bigint,
  'startHour' : bigint,
}
export interface ToDo {
  'id' : bigint,
  'title' : string,
  'timeSpent' : bigint,
  'owner' : Principal,
  'createdAt' : bigint,
  'completed' : boolean,
  'dueDate' : [] | [bigint],
  'description' : string,
  'timerSeconds' : [] | [bigint],
  'category' : string,
  'priority' : Priority,
  'subtasks' : Array<Subtask>,
}
export interface UserAccess {
  'accessLevel' : UserRole,
  'rfidUid' : string,
  'accessWindow' : Array<TimeSlot>,
  'name' : string,
  'role' : UserRole,
  'isActive' : boolean,
  'email' : string,
  'pinCode' : string,
  'failedAttempts' : bigint,
  'lastAccess' : bigint,
}
export interface UserProfile {
  'rfidUid' : string,
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'totalCompleted' : bigint,
  'lastCompletedDate' : [] | [bigint],
  'unlockedBadges' : Array<string>,
  'longestStreak' : bigint,
  'currentStreak' : bigint,
  'points' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDevice' : ActorMethod<[string, string, string], undefined>,
  'addSmartRule' : ActorMethod<[SmartRule], undefined>,
  'addUser' : ActorMethod<[UserAccess], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignDeviceToAdmin' : ActorMethod<[string], undefined>,
  'completeTodo' : ActorMethod<[bigint], undefined>,
  'createDefaultStats' : ActorMethod<[], undefined>,
  'createTodo' : ActorMethod<
    [
      string,
      string,
      Priority,
      string,
      [] | [bigint],
      Array<Subtask>,
      [] | [bigint],
    ],
    bigint
  >,
  'deleteTodo' : ActorMethod<[bigint], undefined>,
  'disableUser' : ActorMethod<[string], undefined>,
  'disableVacationMode' : ActorMethod<[], undefined>,
  'enableUser' : ActorMethod<[string], undefined>,
  'enableVacationMode' : ActorMethod<[], undefined>,
  'finishTimer' : ActorMethod<[bigint, bigint], undefined>,
  'getAccessEvents' : ActorMethod<[], Array<AccessEvent>>,
  'getAdminDashboardData' : ActorMethod<
    [],
    {
      'activeUsers' : bigint,
      'vacationMode' : boolean,
      'disabledUsers' : bigint,
      'failedAccessLast24h' : bigint,
      'accessEventFeed' : Array<AccessEvent>,
      'deviceStatuses' : Array<[string, DeviceStatus]>,
      'guestUsers' : bigint,
      'totalUsers' : bigint,
      'activeSmartRulesCount' : bigint,
    }
  >,
  'getAllDeviceStatuses' : ActorMethod<[], Array<[string, DeviceStatus]>>,
  'getAllDevices' : ActorMethod<[], Array<[string, DeviceInfo]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDefaultDeviceStatus' : ActorMethod<[], DeviceStatus>,
  'getDeviceById' : ActorMethod<
    [string],
    {
      'id' : string,
      'status' : DeviceStatus,
      'name' : string,
      'isConnected' : boolean,
      'lastSync' : Time,
    }
  >,
  'getDeviceCount' : ActorMethod<[], bigint>,
  'getDeviceList' : ActorMethod<[], Array<DeviceInfo>>,
  'getDeviceNameCache' : ActorMethod<[], Array<[string, string]>>,
  'getDeviceStatsById' : ActorMethod<[string], [] | [DeviceStatus]>,
  'getDeviceStatusById' : ActorMethod<[string], [] | [DeviceStatus]>,
  'getEventLogs' : ActorMethod<[], Array<LogEvent>>,
  'getFailedAccessEventsLast24h' : ActorMethod<[], Array<AccessEvent>>,
  'getMyStats' : ActorMethod<[], UserStats>,
  'getSecurityDecoyStatus' : ActorMethod<[], boolean>,
  'getSmartRuleExecutionLog' : ActorMethod<[], Array<SmartRuleLog>>,
  'getSmartRules' : ActorMethod<[], Array<SmartRule>>,
  'getTodoStats' : ActorMethod<
    [],
    {
      'total' : bigint,
      'pending' : bigint,
      'completed' : bigint,
      'overdue' : bigint,
      'urgent' : bigint,
    }
  >,
  'getTodos' : ActorMethod<[], Array<ToDo>>,
  'getTodosByCategory' : ActorMethod<[string], Array<ToDo>>,
  'getUserAccessWindow' : ActorMethod<[string], Array<TimeSlot>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsers' : ActorMethod<[], Array<UserAccess>>,
  'getVacationModeStatus' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isDeviceAdmin' : ActorMethod<[string], undefined>,
  'logSmartRuleExecution' : ActorMethod<
    [string, string, string, boolean],
    undefined
  >,
  'recordAccessEvent' : ActorMethod<[AccessEvent], undefined>,
  'removeSmartRule' : ActorMethod<[string], undefined>,
  'removeUser' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserAccessWindow' : ActorMethod<[string, Array<TimeSlot>], undefined>,
  'simulateAccessAttempt' : ActorMethod<
    [string, string, string, string, bigint, bigint],
    boolean
  >,
  'startTimer' : ActorMethod<[bigint], undefined>,
  'syncDevice' : ActorMethod<[string], undefined>,
  'toggleDefaultDeviceLock' : ActorMethod<[], undefined>,
  'toggleDeviceLock' : ActorMethod<[string], undefined>,
  'toggleHolidayLights' : ActorMethod<[boolean], undefined>,
  'updateDeviceStatus' : ActorMethod<[string, DeviceStatus], undefined>,
  'updateTodo' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [string],
      [] | [boolean],
      [] | [Priority],
      [] | [string],
      [] | [bigint],
      [] | [Array<Subtask>],
      [] | [bigint],
      [] | [bigint],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];