/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TimeSlot {
    day: bigint;
    endHour: bigint;
    startHour: bigint;
}
export interface UserAccess {
    accessLevel: UserRole;
    rfidUid: string;
    accessWindow: Array<TimeSlot>;
    name: string;
    role: UserRole;
    isActive: boolean;
    email: string;
    pinCode: string;
    failedAttempts: bigint;
    lastAccess: bigint;
}
export type Time = bigint;
export interface SmartRuleLog {
    ruleName: string;
    triggerCondition: string;
    timestamp: Time;
    outcome: boolean;
    actionTaken: string;
}
export interface SmartRule {
    ruleName: string;
    action: string;
    active: boolean;
    createdBy: string;
    deviceId: string;
    users: Array<string>;
    schedule: string;
    triggers: Array<string>;
}
export interface DeviceStatus {
    batteryLevel: bigint;
    tamperDetected: boolean;
    wifiSignalStrength: bigint;
    isLocked: boolean;
    emergencyMode: boolean;
    firmwareVersion: string;
    lastSync: bigint;
    currentUsers: bigint;
}
export interface Subtask {
    id: bigint;
    text: string;
    completed: boolean;
}
export interface DeviceInfo {
    status: DeviceStatus;
    isConnected: boolean;
    deviceId: string;
    deviceName: string;
    lastSync: Time;
}
export interface LogEvent {
    code: string;
    level: string;
    message: string;
    deviceId: string;
    timestamp: Time;
}
export interface ToDo {
    id: bigint;
    title: string;
    timeSpent: bigint;
    owner: Principal;
    createdAt: bigint;
    completed: boolean;
    dueDate?: bigint;
    description: string;
    timerSeconds?: bigint;
    category: string;
    priority: Priority;
    subtasks: Array<Subtask>;
}
export interface AccessEvent {
    rfidUid: string;
    method: string;
    userEmail: string;
    timestamp: bigint;
    success: boolean;
    location: string;
    eventType: string;
}
export interface UserStats {
    totalCompleted: bigint;
    lastCompletedDate?: bigint;
    unlockedBadges: Array<string>;
    longestStreak: bigint;
    currentStreak: bigint;
    points: bigint;
}
export interface UserProfile {
    rfidUid: string;
    name: string;
    email: string;
}
export enum Priority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDevice(deviceId: string, deviceName: string, encryptedCredentials: string): Promise<void>;
    addSmartRule(rule: SmartRule): Promise<void>;
    addUser(user: UserAccess): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignDeviceToAdmin(deviceId: string): Promise<void>;
    completeTodo(id: bigint): Promise<void>;
    createDefaultStats(): Promise<void>;
    createTodo(title: string, description: string, priority: Priority, category: string, dueDate: bigint | null, subtasks: Array<Subtask>, timerSeconds: bigint | null): Promise<bigint>;
    deleteTodo(id: bigint): Promise<void>;
    disableUser(uid: string): Promise<void>;
    disableVacationMode(): Promise<void>;
    enableUser(uid: string): Promise<void>;
    enableVacationMode(): Promise<void>;
    finishTimer(todoId: bigint, timeSpent: bigint): Promise<void>;
    getAccessEvents(): Promise<Array<AccessEvent>>;
    getAdminDashboardData(): Promise<{
        activeUsers: bigint;
        vacationMode: boolean;
        disabledUsers: bigint;
        failedAccessLast24h: bigint;
        accessEventFeed: Array<AccessEvent>;
        deviceStatuses: Array<[string, DeviceStatus]>;
        guestUsers: bigint;
        totalUsers: bigint;
        activeSmartRulesCount: bigint;
    }>;
    getAllDeviceStatuses(): Promise<Array<[string, DeviceStatus]>>;
    getAllDevices(): Promise<Array<[string, DeviceInfo]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDefaultDeviceStatus(): Promise<DeviceStatus>;
    getDeviceById(deviceId: string): Promise<{
        id: string;
        status: DeviceStatus;
        name: string;
        isConnected: boolean;
        lastSync: Time;
    }>;
    getDeviceCount(): Promise<bigint>;
    getDeviceList(): Promise<Array<DeviceInfo>>;
    getDeviceNameCache(): Promise<Array<[string, string]>>;
    getDeviceStatsById(deviceId: string): Promise<DeviceStatus | null>;
    getDeviceStatusById(deviceId: string): Promise<DeviceStatus | null>;
    getEventLogs(): Promise<Array<LogEvent>>;
    getFailedAccessEventsLast24h(): Promise<Array<AccessEvent>>;
    getMyStats(): Promise<UserStats>;
    getSecurityDecoyStatus(): Promise<boolean>;
    getSmartRuleExecutionLog(): Promise<Array<SmartRuleLog>>;
    getSmartRules(): Promise<Array<SmartRule>>;
    getTodoStats(): Promise<{
        total: bigint;
        pending: bigint;
        completed: bigint;
        overdue: bigint;
        urgent: bigint;
    }>;
    getTodos(): Promise<Array<ToDo>>;
    getTodosByCategory(category: string): Promise<Array<ToDo>>;
    getUserAccessWindow(uid: string): Promise<Array<TimeSlot>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUsers(): Promise<Array<UserAccess>>;
    getVacationModeStatus(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isDeviceAdmin(deviceId: string): Promise<void>;
    logSmartRuleExecution(ruleName: string, triggerCondition: string, actionTaken: string, outcome: boolean): Promise<void>;
    recordAccessEvent(event: AccessEvent): Promise<void>;
    removeSmartRule(ruleName: string): Promise<void>;
    removeUser(uid: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setUserAccessWindow(uid: string, accessWindow: Array<TimeSlot>): Promise<void>;
    simulateAccessAttempt(rfidUid: string, userEmail: string, location: string, method: string, dayOfWeek: bigint, hourOfDay: bigint): Promise<boolean>;
    startTimer(todoId: bigint): Promise<void>;
    syncDevice(deviceId: string): Promise<void>;
    toggleDefaultDeviceLock(): Promise<void>;
    toggleDeviceLock(deviceId: string): Promise<void>;
    toggleHolidayLights(status: boolean): Promise<void>;
    updateDeviceStatus(deviceId: string, newStatus: DeviceStatus): Promise<void>;
    updateTodo(id: bigint, newTitle: string | null, newDescription: string | null, completed: boolean | null, priority: Priority | null, category: string | null, dueDate: bigint | null, subtasks: Array<Subtask> | null, timerSeconds: bigint | null, timeSpent: bigint | null): Promise<void>;
}
import type { DeviceStatus as _DeviceStatus, Priority as _Priority, Subtask as _Subtask, TimeSlot as _TimeSlot, ToDo as _ToDo, UserAccess as _UserAccess, UserProfile as _UserProfile, UserRole as _UserRole, UserStats as _UserStats } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDevice(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDevice(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDevice(arg0, arg1, arg2);
            return result;
        }
    }
    async addSmartRule(arg0: SmartRule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSmartRule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSmartRule(arg0);
            return result;
        }
    }
    async addUser(arg0: UserAccess): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUser(to_candid_UserAccess_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUser(to_candid_UserAccess_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignDeviceToAdmin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignDeviceToAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignDeviceToAdmin(arg0);
            return result;
        }
    }
    async completeTodo(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTodo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTodo(arg0);
            return result;
        }
    }
    async createDefaultStats(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDefaultStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDefaultStats();
            return result;
        }
    }
    async createTodo(arg0: string, arg1: string, arg2: Priority, arg3: string, arg4: bigint | null, arg5: Array<Subtask>, arg6: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTodo(arg0, arg1, to_candid_Priority_n5(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTodo(arg0, arg1, to_candid_Priority_n5(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async deleteTodo(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTodo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTodo(arg0);
            return result;
        }
    }
    async disableUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disableUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disableUser(arg0);
            return result;
        }
    }
    async disableVacationMode(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disableVacationMode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disableVacationMode();
            return result;
        }
    }
    async enableUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enableUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enableUser(arg0);
            return result;
        }
    }
    async enableVacationMode(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enableVacationMode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enableVacationMode();
            return result;
        }
    }
    async finishTimer(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.finishTimer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finishTimer(arg0, arg1);
            return result;
        }
    }
    async getAccessEvents(): Promise<Array<AccessEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccessEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccessEvents();
            return result;
        }
    }
    async getAdminDashboardData(): Promise<{
        activeUsers: bigint;
        vacationMode: boolean;
        disabledUsers: bigint;
        failedAccessLast24h: bigint;
        accessEventFeed: Array<AccessEvent>;
        deviceStatuses: Array<[string, DeviceStatus]>;
        guestUsers: bigint;
        totalUsers: bigint;
        activeSmartRulesCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminDashboardData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminDashboardData();
            return result;
        }
    }
    async getAllDeviceStatuses(): Promise<Array<[string, DeviceStatus]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeviceStatuses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeviceStatuses();
            return result;
        }
    }
    async getAllDevices(): Promise<Array<[string, DeviceInfo]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDevices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDevices();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDefaultDeviceStatus(): Promise<DeviceStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultDeviceStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultDeviceStatus();
            return result;
        }
    }
    async getDeviceById(arg0: string): Promise<{
        id: string;
        status: DeviceStatus;
        name: string;
        isConnected: boolean;
        lastSync: Time;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeviceById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeviceById(arg0);
            return result;
        }
    }
    async getDeviceCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeviceCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeviceCount();
            return result;
        }
    }
    async getDeviceList(): Promise<Array<DeviceInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeviceList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeviceList();
            return result;
        }
    }
    async getDeviceNameCache(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeviceNameCache();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeviceNameCache();
            return result;
        }
    }
    async getDeviceStatsById(arg0: string): Promise<DeviceStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeviceStatsById(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeviceStatsById(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeviceStatusById(arg0: string): Promise<DeviceStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeviceStatusById(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeviceStatusById(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventLogs(): Promise<Array<LogEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventLogs();
            return result;
        }
    }
    async getFailedAccessEventsLast24h(): Promise<Array<AccessEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFailedAccessEventsLast24h();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFailedAccessEventsLast24h();
            return result;
        }
    }
    async getMyStats(): Promise<UserStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStats();
                return from_candid_UserStats_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStats();
            return from_candid_UserStats_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSecurityDecoyStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getSecurityDecoyStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSecurityDecoyStatus();
            return result;
        }
    }
    async getSmartRuleExecutionLog(): Promise<Array<SmartRuleLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSmartRuleExecutionLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSmartRuleExecutionLog();
            return result;
        }
    }
    async getSmartRules(): Promise<Array<SmartRule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSmartRules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSmartRules();
            return result;
        }
    }
    async getTodoStats(): Promise<{
        total: bigint;
        pending: bigint;
        completed: bigint;
        overdue: bigint;
        urgent: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodoStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodoStats();
            return result;
        }
    }
    async getTodos(): Promise<Array<ToDo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodos();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodos();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodosByCategory(arg0: string): Promise<Array<ToDo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodosByCategory(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodosByCategory(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAccessWindow(arg0: string): Promise<Array<TimeSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAccessWindow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAccessWindow(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(): Promise<Array<UserAccess>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVacationModeStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getVacationModeStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVacationModeStatus();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isDeviceAdmin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.isDeviceAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isDeviceAdmin(arg0);
            return result;
        }
    }
    async logSmartRuleExecution(arg0: string, arg1: string, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logSmartRuleExecution(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logSmartRuleExecution(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async recordAccessEvent(arg0: AccessEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAccessEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAccessEvent(arg0);
            return result;
        }
    }
    async removeSmartRule(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSmartRule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSmartRule(arg0);
            return result;
        }
    }
    async removeUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUser(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setUserAccessWindow(arg0: string, arg1: Array<TimeSlot>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserAccessWindow(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserAccessWindow(arg0, arg1);
            return result;
        }
    }
    async simulateAccessAttempt(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.simulateAccessAttempt(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.simulateAccessAttempt(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async startTimer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startTimer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startTimer(arg0);
            return result;
        }
    }
    async syncDevice(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.syncDevice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.syncDevice(arg0);
            return result;
        }
    }
    async toggleDefaultDeviceLock(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleDefaultDeviceLock();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleDefaultDeviceLock();
            return result;
        }
    }
    async toggleDeviceLock(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleDeviceLock(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleDeviceLock(arg0);
            return result;
        }
    }
    async toggleHolidayLights(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleHolidayLights(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleHolidayLights(arg0);
            return result;
        }
    }
    async updateDeviceStatus(arg0: string, arg1: DeviceStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeviceStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeviceStatus(arg0, arg1);
            return result;
        }
    }
    async updateTodo(arg0: bigint, arg1: string | null, arg2: string | null, arg3: boolean | null, arg4: Priority | null, arg5: string | null, arg6: bigint | null, arg7: Array<Subtask> | null, arg8: bigint | null, arg9: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTodo(arg0, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTodo(arg0, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg9));
            return result;
        }
    }
}
function from_candid_Priority_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ToDo_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToDo): ToDo {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserAccess_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserAccess): UserAccess {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserStats_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStats): UserStats {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DeviceStatus]): DeviceStatus | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalCompleted: bigint;
    lastCompletedDate: [] | [bigint];
    unlockedBadges: Array<string>;
    longestStreak: bigint;
    currentStreak: bigint;
    points: bigint;
}): {
    totalCompleted: bigint;
    lastCompletedDate?: bigint;
    unlockedBadges: Array<string>;
    longestStreak: bigint;
    currentStreak: bigint;
    points: bigint;
} {
    return {
        totalCompleted: value.totalCompleted,
        lastCompletedDate: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.lastCompletedDate)),
        unlockedBadges: value.unlockedBadges,
        longestStreak: value.longestStreak,
        currentStreak: value.currentStreak,
        points: value.points
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    timeSpent: bigint;
    owner: Principal;
    createdAt: bigint;
    completed: boolean;
    dueDate: [] | [bigint];
    description: string;
    timerSeconds: [] | [bigint];
    category: string;
    priority: _Priority;
    subtasks: Array<_Subtask>;
}): {
    id: bigint;
    title: string;
    timeSpent: bigint;
    owner: Principal;
    createdAt: bigint;
    completed: boolean;
    dueDate?: bigint;
    description: string;
    timerSeconds?: bigint;
    category: string;
    priority: Priority;
    subtasks: Array<Subtask>;
} {
    return {
        id: value.id,
        title: value.title,
        timeSpent: value.timeSpent,
        owner: value.owner,
        createdAt: value.createdAt,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.dueDate)),
        description: value.description,
        timerSeconds: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.timerSeconds)),
        category: value.category,
        priority: from_candid_Priority_n20(_uploadFile, _downloadFile, value.priority),
        subtasks: value.subtasks
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accessLevel: _UserRole;
    rfidUid: string;
    accessWindow: Array<_TimeSlot>;
    name: string;
    role: _UserRole;
    isActive: boolean;
    email: string;
    pinCode: string;
    failedAttempts: bigint;
    lastAccess: bigint;
}): {
    accessLevel: UserRole;
    rfidUid: string;
    accessWindow: Array<TimeSlot>;
    name: string;
    role: UserRole;
    isActive: boolean;
    email: string;
    pinCode: string;
    failedAttempts: bigint;
    lastAccess: bigint;
} {
    return {
        accessLevel: from_candid_UserRole_n10(_uploadFile, _downloadFile, value.accessLevel),
        rfidUid: value.rfidUid,
        accessWindow: value.accessWindow,
        name: value.name,
        role: from_candid_UserRole_n10(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: value.email,
        pinCode: value.pinCode,
        failedAttempts: value.failedAttempts,
        lastAccess: value.lastAccess
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "medium" in value ? Priority.medium : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ToDo>): Array<ToDo> {
    return value.map((x)=>from_candid_ToDo_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserAccess>): Array<UserAccess> {
    return value.map((x)=>from_candid_UserAccess_n23(_uploadFile, _downloadFile, x));
}
function to_candid_Priority_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserAccess_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserAccess): _UserAccess {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority | null): [] | [_Priority] {
    return value === null ? candid_none() : candid_some(to_candid_Priority_n5(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Subtask> | null): [] | [Array<_Subtask>] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accessLevel: UserRole;
    rfidUid: string;
    accessWindow: Array<TimeSlot>;
    name: string;
    role: UserRole;
    isActive: boolean;
    email: string;
    pinCode: string;
    failedAttempts: bigint;
    lastAccess: bigint;
}): {
    accessLevel: _UserRole;
    rfidUid: string;
    accessWindow: Array<_TimeSlot>;
    name: string;
    role: _UserRole;
    isActive: boolean;
    email: string;
    pinCode: string;
    failedAttempts: bigint;
    lastAccess: bigint;
} {
    return {
        accessLevel: to_candid_UserRole_n3(_uploadFile, _downloadFile, value.accessLevel),
        rfidUid: value.rfidUid,
        accessWindow: value.accessWindow,
        name: value.name,
        role: to_candid_UserRole_n3(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: value.email,
        pinCode: value.pinCode,
        failedAttempts: value.failedAttempts,
        lastAccess: value.lastAccess
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
